networks:
  my_network:
services:
  db:
    image: postgres
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - my_network
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      retries: 100
  redis:
    image: redis
    networks:
      - my_network
    ports:
      - 6380:6379
  backend:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    build: ./backend
    networks:
      - my_network
    ports:
      - 8000:8089